### ISSUE TITLE
About uiwebview

### ISSUE THREAD

**Issue by mesutgok** [thatzprem/AuthenticationChallenge-Example#1]
Hi Prem,

Great tutorial thanks.
How to work authentication success after uiwebview ?

**Comment by mesutgok** [comment]
I have fixed problem. 

Add webview controller. 

// ViewController.h 
@property (strong,nonatomic) IBOutlet UIWebView *webview;

//ViewController.m

connectionDidFinishLoading add code

_loginPage.hidden = YES;
_webview.hidden = NO;
NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:@"https://domain.com/home"]];
[_webview loadRequest:request];

**Comment by thatzprem** [comment]
Hi @mesutgok - Did't get a chance to take a look at the issue anytime before than now. Glad to hear the  issue is fixed! - Thanks.
